---
apiVersion: v1
kind: service
metadata:
  name: gol-dev
spec:
  selector:
    app: gol
    env: dev
  type: NodePort
  ports:
    - targetport: 8080
      port: 8080
      nodePort: 32766
          