---
apiVersion: v1
kind: Pod
metadata:
  name: gameoflife
spec:
  containers:
    - name: gameoflife
      image: maheswarimurali/gameoflife
      ports:
        - name: golhttpport
          containerPort: 8080
          protocol: TCP
          

