---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: mypod
spec:
  containers:
    - name: web 
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
