---
apiVersion: v1
kind: Pod
metadata:
  name: spc
spec:
  containers:
    - name: springpetclinic
      image: maheswarimurali/spc
      ports:
        - name: spc-port
          containerPort: 8080
          protocol: TCP
          
