---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
  labels:
    app: tomcat
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: tomcat
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:8
        ports:
          - containerPort: 8080
            protocol: TCP